version: "3.9"

services:
  db:
    image: postgres
    container_name: quarkushop_db
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - quarkushop_vol:/var/lib/postgresql/data

volumes:
  quarkushop_vol: {}